-- Phase 1: helpdesk, gate, ledger, billing, payments.
--
-- Two things here are the reason this migration exists rather than being generated:
-- the RLS policies for every new tenant table, and the database-level enforcement of
-- ledger immutability. Neither can be expressed in a schema definition.

-- ---------------------------------------------------------------- enums
DO $$ BEGIN
  CREATE TYPE ticket_status AS ENUM ('open','in_progress','resolved','closed','reopened');
  CREATE TYPE ticket_priority AS ENUM ('low','normal','high','urgent');
  CREATE TYPE ticket_location_type AS ENUM ('unit','tower','floor','amenity','common');
  CREATE TYPE ticket_event_type AS ENUM ('comment','status_change','assignment',
    'internal_note','attachment','rating','reopen','escalation');
  CREATE TYPE ticket_event_visibility AS ENUM ('public','staff_only');
  CREATE TYPE attachment_kind AS ENUM ('photo','video','voice','document');
  CREATE TYPE visitor_category AS ENUM ('guest','delivery','cab','courier','service','staff');
  CREATE TYPE pass_status AS ENUM ('active','used','expired','revoked');
  CREATE TYPE gate_direction AS ENUM ('entry','exit');
  CREATE TYPE approval_state AS ENUM ('pending','approved','denied','auto_approved',
    'timed_out','escalated');
  CREATE TYPE approval_rung AS ENUM ('push','ivr','sms','standing_rule','mc_escalation');
  CREATE TYPE standing_action AS ENUM ('auto_approve','ask_to_wait','deny');
  CREATE TYPE sos_type AS ENUM ('medical','fire','gas','security');
  CREATE TYPE account_type AS ENUM ('asset','liability','income','expense','equity');
  CREATE TYPE journal_source_type AS ENUM ('invoice','receipt','payment','adjustment',
    'opening','contra');
  CREATE TYPE period_status AS ENUM ('open','locked');
  CREATE TYPE invoice_status AS ENUM ('draft','issued','partially_paid','paid','void');
  CREATE TYPE billing_formula AS ENUM ('flat','per_sqft','per_bhk','per_meter',
    'percentage','manual');
  CREATE TYPE payment_method AS ENUM ('upi','card','netbanking','neft','cash','cheque');
  CREATE TYPE payee_type AS ENUM ('society','person');
  CREATE TYPE destination_mode AS ENUM ('route_linked','direct_merchant');
  CREATE TYPE destination_status AS ENUM ('pending','verified','failed','disabled');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Table definitions are generated by Drizzle Kit from packages/db/src/schema.ts.
-- Run `npm run db:generate` to emit them, then this file's policy blocks apply on top.

-- ------------------------------------------------ ledger immutability
--
-- Posted journal entries are never edited. Corrections are reversing entries.
--
-- This is enforced twice on purpose: the grant stops the application role, and the
-- trigger stops anyone reaching the table another way (a migration, a console, a
-- future service). Application discipline is not a control — a control is something
-- that holds when the application is wrong.

CREATE OR REPLACE FUNCTION reject_ledger_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION
    'Posted ledger entries are immutable. Post a reversing entry instead of altering %.',
    TG_TABLE_NAME
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_journal_entries_immutable ON journal_entries;
CREATE TRIGGER trg_journal_entries_immutable
  BEFORE UPDATE OR DELETE ON journal_entries
  FOR EACH ROW EXECUTE FUNCTION reject_ledger_mutation();

DROP TRIGGER IF EXISTS trg_journal_lines_immutable ON journal_lines;
CREATE TRIGGER trg_journal_lines_immutable
  BEFORE UPDATE OR DELETE ON journal_lines
  FOR EACH ROW EXECUTE FUNCTION reject_ledger_mutation();

REVOKE UPDATE, DELETE ON journal_entries FROM watchmygate_app;
REVOKE UPDATE, DELETE ON journal_lines   FROM watchmygate_app;
GRANT  INSERT, SELECT  ON journal_entries TO watchmygate_app;
GRANT  INSERT, SELECT  ON journal_lines   TO watchmygate_app;

-- ------------------------------------------------------- line integrity
-- Exactly one side per line. Prevents the classic "both zero" or "both set" row that
-- silently unbalances a report months later.
ALTER TABLE journal_lines
  DROP CONSTRAINT IF EXISTS ck_line_non_negative,
  DROP CONSTRAINT IF EXISTS ck_line_one_sided;
ALTER TABLE journal_lines
  ADD CONSTRAINT ck_line_non_negative CHECK (debit >= 0 AND credit >= 0),
  ADD CONSTRAINT ck_line_one_sided    CHECK ((debit = 0) <> (credit = 0));

-- Ratings are 1..5 or absent.
ALTER TABLE tickets DROP CONSTRAINT IF EXISTS ck_ticket_rating;
ALTER TABLE tickets
  ADD CONSTRAINT ck_ticket_rating CHECK (rating IS NULL OR (rating BETWEEN 1 AND 5));

-- ---------------------------------------------------- Row-Level Security
-- Same pattern and the same nullif() reasoning as migration 0001.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'ticket_categories', 'tickets', 'ticket_events', 'ticket_subscribers', 'attachments',
    'society_signing_keys', 'gates', 'visitor_passes', 'gate_events', 'approvals',
    'approval_rungs', 'standing_rules', 'sos_alerts', 'watchlist',
    'ledger_accounts', 'accounting_periods', 'journal_entries', 'journal_lines',
    'charge_types', 'gst_rules', 'invoices', 'invoice_lines',
    'payment_destinations', 'charge_type_routing', 'receipts', 'receipt_allocations'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I
         USING      (society_id = nullif(current_setting(''app.society_id'', true), '''')::uuid)
         WITH CHECK (society_id = nullif(current_setting(''app.society_id'', true), '''')::uuid)',
      t
    );
  END LOOP;
END $$;

-- ------------------------------------------- amenity double-booking guard
-- Application-level conflict checks race under concurrency and eventually lose. An
-- exclusion constraint is what actually prevents two families booking the party hall
-- for the same evening.
CREATE TABLE IF NOT EXISTS amenities (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  society_id  uuid NOT NULL REFERENCES societies(id),
  name        varchar(120) NOT NULL,
  capacity    integer,
  slot_minutes integer NOT NULL DEFAULT 60,
  is_paid     boolean NOT NULL DEFAULT false,
  rate        numeric(18,4) NOT NULL DEFAULT 0,
  rules       jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS amenity_bookings (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  society_id uuid NOT NULL REFERENCES societies(id),
  amenity_id uuid NOT NULL REFERENCES amenities(id),
  unit_id    uuid NOT NULL,
  booked_by  uuid NOT NULL,
  starts_at  timestamptz NOT NULL,
  ends_at    timestamptz NOT NULL,
  status     varchar(16) NOT NULL DEFAULT 'confirmed',
  invoice_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_booking_range CHECK (ends_at > starts_at),
  CONSTRAINT ex_amenity_no_overlap EXCLUDE USING gist (
    amenity_id WITH =,
    tstzrange(starts_at, ends_at) WITH &&
  ) WHERE (status = 'confirmed')
);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['amenities', 'amenity_bookings'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I
         USING      (society_id = nullif(current_setting(''app.society_id'', true), '''')::uuid)
         WITH CHECK (society_id = nullif(current_setting(''app.society_id'', true), '''')::uuid)',
      t
    );
  END LOOP;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON amenities, amenity_bookings TO watchmygate_app;
